# -*- coding: utf-8 -*-
"""Feature Engineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SPNqygc3ScL900CkGVxulL2goBl9_PbR
"""

from sklearn.feature_selection import SelectKBest

from pandas import read_csv
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
import pandas as pd
filename='/content/sample_data/pima-indians-diabetes.data.csv'
names=['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
print(names)
dataframe=read_csv(filename, names=names)
array=dataframe.values
X = array[:,0:8]
Y = array[:,8]
test=SelectKBest(score_func=chi2, k=4)
fit=test.fit(X,Y)
set_printoptions(precision=3)
print(fit.scores_)
features=fit.transform(X)
print(features[0:5,:])

from pandas import read_csv
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
filename='/content/sample_data/pima-indians-diabetes.data.csv'
names=['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe=read_csv(filename, names=names)
print(dataframe)
array=dataframe.values
X = array[:,0:8]
Y = array[:,8]
model=LogisticRegression(max_iter=400)
rfe=RFE(estimator=model, n_features_to_select=3)
fit=rfe.fit(X,Y)